---
- hosts: integration 
  become: True
  tasks:

    - name: Deploy html code integration
      git:
        repo: 'https://github.com/karandavuluri/web-server'
        dest: /home/ubuntu/
        version: integration
      copy:
        src: /home/ubuntu/web-server/index.html
        dest: /var/www/html/  

- hosts: preprod 
  become: True
  tasks:
    - name: Deploy html code preprod
      git:
        repo: 'https://github.com/karandavuluri/web-server'
        dest: /home/ubuntu/
        version: preprod
      copy:
        src: /home/ubuntu/web-server/index.html
        dest: /var/www/html/

- hosts: prod
  become: True
  tasks:
    - name: Deploy html code prod
      git:
        repo: 'https://github.com/karandavuluri/web-server'
        dest: /home/ubuntu/
        version: master
      copy:
        src: /home/ubuntu/web-server/index.html
        dest: /var/www/html/
...