---
- hosts: prod 
  become: True
  tasks:
    - name: Install packages
      apt:
        name: apache2
        update_cache: yes
        state: "present"
    # - name: ensure a directory exists
    #   file:
    #     path: $HOME/project
    #     state: directory
    # - name: integration Deploy
    #   git:
    #     repo: 'https://github.com/karandavuluri/web-server'
    #     dest: $HOME/project
    #     version: integration
    - name: copy prod  
      copy:
        src: index.html
        dest: /var/www/html/       
...