---
- hosts: integration 
  become: True
  tasks:
    - name: Deploy html code
      git:
        repo: 'https://github.com/karandavuluri/web-server'
        dest: /var/www/html/
        version: integration

- hosts: preprod 
  become: True
  tasks:
    - name: Deploy html code
      git:
        repo: 'https://github.com/karandavuluri/web-server'
        dest: /var/www/html/
        version: preprod

- hosts: prod
  become: True
  tasks:
    - name: Deploy html code
      git:
        repo: 'https://github.com/karandavuluri/web-server'
        dest: /var/www/html/
        version: master
...