---
- hosts: integration 
  become: True
  tasks:
    - name: Install packages
      apt:
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: ensure a directory exists
      file:
        path: $HOME/project
        state: directory
    - name: integration Deploy
      git:
        repo: 'https://github.com/karandavuluri/web-server'
        dest: $HOME/project
        version: integration
    - name: copy integration  
      copy:
        src: $HOME/project/web-server/index.html
        dest: /var/www/html/

- hosts: preprod 
  become: True
  tasks:
    - name: Deploy html code preprod
      git:
        repo: 'https://github.com/karandavuluri/web-server'
        dest: /home/ubuntu/
        version: preprod
    - name: copy preprod    
      copy:
        src: /home/ubuntu/web-server/index.html
        dest: /var/www/html/

- hosts: prod
  become: True
  tasks:
    - name: Deploy html code prod
      git:
        repo: 'https://github.com/karandavuluri/web-server'
        dest: /home/ubuntu/
        version: master
    - name: copy prod
      copy:
        src: /home/ubuntu/web-server/index.html
        dest: /var/www/html/
...